name: Building

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_node:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Run clean install
      run: npm ci --prefix ./server
    - name: Test Node application
      run: npm run test --prefix ./server
    - name: Build the node application
      run: npm run build --prefix ./server --if-present
    
  
  build_react:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run clean install
      run: yarn --cwd ./client run ci
    - name: Test React application
      run: yarn --cwd ./client run test
    - name: Build the React application
      run: yarn --cwd ./client run build
